version: '3'
services:

  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
    - 27017:27017

  tweet_collector:
    build: tweet_collector/
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb
  
  etl_job: #run container with this name
    build: etl_job/
    volumes:
    - ./etl_job/:/app
    depends_on:
    - mongodb
    - postgresdb

  postgresdb: # Postgress container to run
    image: postgres
    container_name: "postgres"
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=tweet_postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tweets